services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuln-web
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: vuln-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password --show_compatibility_56=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
